### ISSUE TITLE
ionosctl server list --cols ServerId shows whole entry not just the severId

### ISSUE THREAD

**Issue by ssingh-ionos** [ionos-cloud/ionosctl#415]
## Description
```
ionosctl server list --all --no-headers --cols Serverid --filters name=nas1
70cd707c-8bde-4465-8c18-5caaccb01abc   87b4a9fe-0d26-4eaf-b094-0d0589889bf7   nas1   ZONE_1   1    1024   INTEL_ICELAKE   RUNNING   AVAILABLE   server   4ddca587-a47f-47fc-a301-955468c24d2e
````

## Expected behavior
```
ionosctl server list --all --no-headers --cols Serverid --filters name=nas1
70cd707c-8bde-4465-8c18-5caaccb01abc 
```

## Environment

Go Version:
```
go version
go version go1.18.1 linux/amd64

```
Ionosctl version:
```
ionosctl version v6.7.3
```
OS:
```
Ubuntu 22.04.3 LTS
```
Shell:
```
bash
```

**Comment by avirtopeanu-ionos** [comment]
Seems to be caused by viper binding to the wrong server `cols` flag - since the new update it now binds to `vm-autoscaling server` regardless of which `server` command you use.

Frankly this is a sign we need to get rid of this technical debt and preferably have a single source of truth for `--cols`, i.e. defining it as a root-level global flag.

Until then, I will patch this to get it working again. Thanks for opening this issue!

**Comment by ssingh-ionos** [comment]
I checked out master and did a local install. I see the same behavior.

```ionosctl --version
ionosctl version DEV-f10b8e4c+
```

Is there a workaround for this while you work on the patch? By workaround mean some other order of filters so that I can get the serverId.

**Comment by avirtopeanu-ionos** [comment]
> Is there a workaround for this while you work on the patch? By workaround mean some other order of filters so that I can get the serverId.

Yes! You can use `-o json` in combination with `jq` to extract the ID: `i server list -a -o json | jq -r '.items[] | .id'`
